fix unhelpful log message with wrong MSVS version
Closes #147

Right now it would crash with this error, instead of returning the helpful message about setting msvs to a different version.

```javascript
    console.log('Invalid msvs_version ' + msvsVersion + '\n');
                                          ^

ReferenceError: msvsVersion is not defined
```